name: CI Tests

on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
    create-archive:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true

            - uses: actions/cache@v2
              with:
                  path: |
                     data/country_osm_grid.sql.gz
                  key: nominatim-country-data-1

            - name: Package tarball
              run: |
                  if [ ! -f data/country_osm_grid.sql.gz ]; then
                      wget --no-verbose -O data/country_osm_grid.sql.gz https://www.nominatim.org/data/country_grid.sql.gz
                  fi
                  cd ..
                  tar czf nominatim-src.tar.bz2 Nominatim
                  mv nominatim-src.tar.bz2 Nominatim

            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v3
              with:
                  name: full-source
                  path: nominatim-src.tar.bz2
                  retention-days: 1

    tests:
        needs: create-archive
        strategy:
            matrix:
                ubuntu: [18, 20]
                include:
                    - ubuntu: 18
                      postgresql: 9.5
                      postgis: 2.5
                      pytest: pytest
                      php: 7.2
                    - ubuntu: 20
                      postgresql: 13
                      postgis: 3
                      pytest: py.test-3
                      php: 7.4

        runs-on: ubuntu-${{ matrix.ubuntu }}.04

        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: full-source

            - name: Unpack Nominatim
              run: tar xf nominatim-src.tar.bz2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug
                  tools: phpunit, phpcs, composer

            - uses: actions/setup-python@v2
              with:
                python-version: 3.6
              if: matrix.ubuntu == 18

            - uses: ./Nominatim/.github/actions/setup-postgresql
              with:
                  postgresql-version: ${{ matrix.postgresql }}
                  postgis-version: ${{ matrix.postgis }}

            - uses: ./Nominatim/.github/actions/build-nominatim
              with:
                  ubuntu: ${{ matrix.ubuntu }}

            - name: Install test prerequsites
              run: sudo apt-get install -y -qq pylint python3-pytest python3-behave python3-pytest-cov php-codecoverage
              if: matrix.ubuntu == 20

            - name: Install test prerequsites
              run: pip3 install pylint==2.6.0 pytest pytest-cov behave==1.2.6
              if: matrix.ubuntu == 18

            - name: PHP linting
              run: phpcs --report-width=120 .
              working-directory: Nominatim

            - name: Python linting
              run: pylint nominatim
              working-directory: Nominatim

            - name: PHP unit tests
              run: phpunit --coverage-clover ../../coverage-php.xml ./
              working-directory: Nominatim/test/php
              if: matrix.ubuntu == 20

            - name: Python unit tests
              run: $PYTEST --cov=nominatim --cov-report=xml test/python
              working-directory: Nominatim
              env:
                PYTEST: ${{ matrix.pytest }}

            - name: BDD tests
              run: |
                  mkdir cov
                  behave -DREMOVE_TEMPLATE=1 -DBUILDDIR=$GITHUB_WORKSPACE/build --format=progress3 -DPHPCOV=./cov
                  composer require phpunit/phpcov:7.0.2
                  vendor/bin/phpcov merge --clover ../../coverage-bdd.xml ./cov
              working-directory: Nominatim/test/bdd
              if: matrix.ubuntu == 20

            - name: BDD tests
              run: |
                  behave -DREMOVE_TEMPLATE=1 -DBUILDDIR=$GITHUB_WORKSPACE/build --format=progress3
              working-directory: Nominatim/test/bdd
              if: matrix.ubuntu == 18

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                files: ./Nominatim/coverage*.xml
                directory: ./
                name: codecov-umbrella
                fail_ci_if_error: false
                path_to_write_report: ./coverage/codecov_report.txt
                verbose: true
              if: matrix.ubuntu == 20


    icu-test:
        needs: create-archive
        strategy:
            matrix:
                ubuntu: [20]
                include:
                    - ubuntu: 20
                      postgresql: 13
                      postgis: 3
                      pytest: py.test-3
                      php: 7.4

        runs-on: ubuntu-${{ matrix.ubuntu }}.04

        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: full-source

            - name: Unpack Nominatim
              run: tar xf nominatim-src.tar.bz2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug
                  tools: phpunit, phpcs, composer

            - uses: actions/setup-python@v2
              with:
                python-version: 3.6
              if: matrix.ubuntu == 18

            - uses: ./Nominatim/.github/actions/setup-postgresql
              with:
                  postgresql-version: ${{ matrix.postgresql }}
                  postgis-version: ${{ matrix.postgis }}

            - uses: ./Nominatim/.github/actions/build-nominatim
              with:
                  ubuntu: ${{ matrix.ubuntu }}

            - name: Install test prerequsites
              run: sudo apt-get install -y -qq python3-behave
              if: matrix.ubuntu == 20

            - name: Install test prerequsites
              run: pip3 install behave==1.2.6
              if: matrix.ubuntu == 18

            - name: BDD tests (icu tokenizer)
              run: |
                  behave -DREMOVE_TEMPLATE=1 -DBUILDDIR=$GITHUB_WORKSPACE/build -DTOKENIZER=icu --format=progress3
              working-directory: Nominatim/test/bdd


    install:
        runs-on: ubuntu-latest
        needs: create-archive

        strategy:
            matrix:
                name: [Ubuntu-18, Ubuntu-20, Centos-8]
                include:
                    - name: Ubuntu-18
                      flavour: ubuntu
                      image: "ubuntu:18.04"
                      ubuntu: 18
                      install_mode: install-nginx
                    - name: Ubuntu-20
                      flavour: ubuntu
                      image: "ubuntu:20.04"
                      ubuntu: 20
                      install_mode: install-apache
                    - name: Centos-8
                      flavour: centos
                      image: "centos:8"

        container:
            image: ${{ matrix.image }}
            env:
                LANG: en_US.UTF-8

        defaults:
            run:
                shell: sudo -Hu nominatim bash --noprofile --norc -eo pipefail {0}

        steps:
            - name: Prepare container (Ubuntu)
              run: |
                  export APT_LISTCHANGES_FRONTEND=none
                  export DEBIAN_FRONTEND=noninteractive
                  apt-get update -qq
                  apt-get install -y git sudo wget
                  ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
              shell: bash
              if: matrix.flavour == 'ubuntu'

            - name: Prepare container (CentOS)
              run: |
                  dnf update -y
                  dnf install -y sudo glibc-langpack-en
              shell: bash
              if: matrix.flavour == 'centos'

            - name: Setup import user
              run: |
                  useradd -m nominatim
                  echo 'nominatim   ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/nominiatim
                  echo "/home/nominatim/Nominatim/vagrant/Install-on-${OS}.sh no $INSTALL_MODE" > /home/nominatim/vagrant.sh
              shell: bash
              env:
                OS: ${{ matrix.name }}
                INSTALL_MODE: ${{ matrix.install_mode }}

            - uses: actions/download-artifact@v2
              with:
                  name: full-source
                  path: /home/nominatim

            - name: Install Nominatim
              run: |
                export USERNAME=nominatim
                export USERHOME=/home/nominatim
                export NOSYSTEMD=yes
                export HAVE_SELINUX=no
                tar xf nominatim-src.tar.bz2
                . vagrant.sh
              working-directory: /home/nominatim

            - name: Prepare import environment
              run: |
                  mv Nominatim/test/testdb/apidb-test-data.pbf test.pbf
                  rm -rf Nominatim
                  mkdir data-env-reverse
              working-directory: /home/nominatim

            - name: Prepare import environment (CentOS)
              run: |
                  sudo ln -s /usr/local/bin/nominatim /usr/bin/nominatim
                  echo NOMINATIM_DATABASE_WEBUSER="apache" > nominatim-project/.env
                  cp nominatim-project/.env data-env-reverse/.env
              working-directory: /home/nominatim
              if: matrix.flavour == 'centos'

            - name: Import
              run: nominatim import --osm-file ../test.pbf
              working-directory: /home/nominatim/nominatim-project

            - name: Import special phrases
              run: nominatim special-phrases --import-from-wiki
              working-directory: /home/nominatim/nominatim-project

            - name: Check full import
              run: nominatim admin --check-database
              working-directory: /home/nominatim/nominatim-project

            - name: Warm up database
              run: nominatim admin --warm
              working-directory: /home/nominatim/nominatim-project

            - name: Prepare update (Ubuntu)
              run: apt-get install -y python3-pip
              shell: bash
              if: matrix.flavour == 'ubuntu'

            - name: Run update
              run: |
                  pip3 install --user osmium
                  nominatim replication --init
                  NOMINATIM_REPLICATION_MAX_DIFF=1 nominatim replication --once
              working-directory: /home/nominatim/nominatim-project

            - name: Run reverse-only import
              run : |
                  echo 'NOMINATIM_DATABASE_DSN="pgsql:dbname=reverse"' >> .env
                  nominatim import --osm-file ../test.pbf --reverse-only --no-updates
              working-directory: /home/nominatim/data-env-reverse

            - name: Check reverse import
              run: nominatim admin --check-database
              working-directory: /home/nominatim/data-env-reverse
